package quackstagram.views;

public enum ColorID {
    BACKGROUND_HEADER,
    BACKGROUND_HEADER_SECONDARY,
    MAIN_BACKGROUND,
    MINOR_BACKGROUND,
    LIKE_BUTTON,
    PRIMARY_lOGIN_BUTTON,
    BACKGROUND_SPACING,
    FOLLOW_BUTTON,
    TEXT_PRIMARY,
    TEXT_SECONDARY,
    ENTER_COMPONENT,
    OPPOSITE_TEXT
}
